[UFS]
path = '../ufs/'
wait_for_delete_dir = 30 # minutes

[TG]
token = ''
telegraph_token = ''
admins_ids = []

[VK]
bot_token = ''
user_token = ''

[MYSQL]
host = ''
port = 3306
username = 'root'
password = ''
database=''

[SERVER]
timezone = 'Europe/Moscow'
